name: CI Meson

on:
  workflow_dispatch:
    
  push:
    paths:
      - "**.c"
      - "**.h"
  pull_request:
    paths:
      - "**.c"
      - "**.h"

jobs:
  build:
    name: Build and Test on ${{ matrix.os }} with Meson v${{ matrix.meson_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        meson_version: ["1.2.0", "1.3.0", "1.4.0"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      # Install dependencies for Ubuntu
      - name: Install dependencies on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libtag1-dev libraylib-dev

      # Install dependencies for macOS
      - name: Install dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install taglib raylib

      # Install dependencies for Windows
      - name: Install dependencies on Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install taglib raylib

      - name: Install Meson and Ninja
        run: python -m pip install meson==${{ matrix.meson_version }} ninja
      
      - name: Configure Project
        run: meson setup builddir/
        env:
          CC: gcc
      
      - name: Run Tests
        run: meson compile -C builddir/ -v
      
